routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@show')->name('welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['role:speler']], function () {
        Route::prefix("tournament")->group(function () {
            Route::resource('signup', 'TournamentUserController');
    });
});
Route::get('tournament/employee/dashboard', function (){
    return redirect()->route('employee.dashboard',['tournament' => \App\Tournament::first()]);
});
Route::group(['prefix' => 'tournaments/{tournament}', 'middleware' => 'role:medewerker|admin'], function() {
    Route::get('/employee/dashboard', 'EmployeesController@index')->name('employee.dashboard');

    Route::get('rounds', 'RoundController@store')->name('round.store');
    Route::put('rounds/{round}', 'RoundController@update')->name('round.update');
    Route::get('rounds/{round}', 'RoundController@show')->name('round.show');
});

Route::group(['middleware' => ['role:admin']], function () {
    Route::resource('tournament', 'TournamentController')->only([
        'create', 'store'
    ]);

});

// Table overview
Route::get('{tournament}/overview', 'TableOverview@show')->name('show.tables');

Route::get('/{tournament}/overview/players', function ($tournament) {

    $latestRound = \App\Round::where('tournament_id', '=',  $tournament)->orderBy('name' ,'desc')->get('id')->first();

    $users = \App\UserRoundTable::join('tournament_user', 'user_round_table.user_id', '=', 'tournament_user.user_id')
        ->join('users', 'tournament_user.user_id', '=', 'users.id')
        ->select('users.name', 'user_round_table.table_id')
        ->where([['user_round_table.round_id', '=', $latestRound->id], ['tournament_user.tournament_id', '=', $tournament], ['tournament_user.status', '=', 1]])
        ->get();

    return $users;

});

//New Route naming.
Route::prefix("tournament/{tournament}")->group(function () {
    Route::prefix("round")->group(function () {
        Route::prefix("{round}")->group(function () {
            Route::resource("history", "UserRoundHistoryController");
        });
    });
});

Route::prefix("{tournament}")->group(function () {
    Route::get('/timer', 'TournamentController@timer')->name('timer');
    Route::get('/gettime', 'TournamentController@gettime')->name('gettime');
    Route::get('/stoptime', 'TournamentController@gettime')->name('stoptime');

    Route::group(['middleware' => ['role:speler']], function () {
        Route::get('/generalranking', 'GeneralRankingController@index')->name('generalranking');

    });
    Route::group(['middleware' => ['role:medewerker|admin']], function () {
        Route::resource('/scanner', 'QrScannerController');
        Route::prefix("employee")->group(function () {
            Route::resource("signups", "TournamentUserEmployeeController");
            Route::resource("score", "ScoreController")->only(['create', 'store']);
            Route::post("score/mail", "ScoreController@mail")->name('score.mail');


            //JS Fetch route
            Route::get('/{table}/round/players', function (\App\Tournament $tournament, \App\Table $table) {

                $table = $tournament->rounds()->orderByDesc("id")->first()->tables()->findOrFail($table->id);
                $users = $table->users(\App\Round::find($table->pivot["round_id"]))->get();

                return $users;

            })->name("round.players");
        });
    });
});
// Audio file path

Route::get('media/{filename}', function ($filename) {
    $path = storage_path('app/public/audio/' . $filename);

    if(!File::exists($path)) abort(404);

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});

resources/views/algemeneRanglijst.blade.php
<script src="{{asset('js/app.js')}}"></script>
<script src="{{asset('js/algemeneranglijst.js')}}"></script>
@extends('layouts.app')
@section('content')
    <form method="get" action="{{ route('generalranking', $tournament ?? '') }}">
    @csrf
    <!-- begin Ranglijst-->
        <div class="container" id="maincontainer">
            <div class="row">
                <div class="col-lg-8 col-md-8 col-sm-6 col-xs-6">

                    <table class="table grid table  table-bordered text-center">
                        <thead>
                        <tr>
                            <th class="table-success">Ranglijst</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr class="breakrow">
                            <td class="text-secondary small bg-light">Klik hier om de table in-uitklappen</td>
                        </tr>
                        <tr>
                            {{--                            <td class="table-info">{{Auth()->user()->name}}</td>--}}
                        </tr>
                        @php
                            $place = 0;
                        @endphp
                        @foreach($generalRankingList as $grl)
                            @php
                                $place++;
                            @endphp
                            <tr>
                                <td style="{{$grl->id === \Illuminate\Support\Facades\Auth::id() ? "background-color: #ededed" : ""}}">{{$place}}. - {{$grl->name}} - {{$grl->score}}</td>
                            </tr>
                            <tr>
                            </tr>
                        @endforeach
                        <tr class="breakrow"></tr>
                        </tbody>
                    </table>
                </div>

                <!-- Einde Ranglijst-->

                <!-- begin Score per ronde-->
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                    <div class="show-qr">
                        <table class="table  table-striped table-bordered text-center">
                            <thead>
                                <tr>
                                    <th class="table-success">Qr Code</th>
                                </tr>
                            </thead>
                            <tbody>
                            <tr class="breakrow">
                                <td class="text-secondary small bg-light">Klik hier om de qr code in-uitklappen</td>
                                <tr>
                                    <td>{!! QrCode::size(300)->generate( $qr_token ) !!}</td>
                                </tr>
                            </tr>
                        </table>

                    </div>
                    <table class="table  table-striped table-bordered text-center">
                        <thead>
                        <tr>
                            <th class="table-success">User score per ronde</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr class="breakrow">
                            <td class="text-secondary small bg-light">Klik hier om de table in-uitklappen</td>
                        </tr>
                        @foreach($UserRoundScore as $scores)
                            <tr>
                                <td>Ronde {{ $scores->round_id}}: {{ $scores->weight}}</td>
                            </tr>
                        @endforeach
                        <tr class="breakrow"></tr>
                        </tbody>
                    </table>
                    <!-- Eind score per ronde-->

                </div>
            </div>
        </div>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/qr_scanner.blade.php
@extends('layouts.app')

@section('content')

    <div class="container-fluid qr_scanner">
        <div class="row">
            <div class="col-12 video-class">
                <video muted playsinline id="qr-video" class=""></video>
            </div>
        </div>
    </div>

    <link href="{{ asset('css/qrScanner.css') }}" rel="stylesheet">

@endsection

resources/views/roundHistory.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            @if(!empty($selectedRound))
                <div class="col-md-12">
                    <h1 class="text-center">{{$tournament->name}}</h1>
                    <h3 class="text-center">
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Ronde: {{$selectedRound->name}}
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                @foreach($allRounds as $round)
                                    <a class="dropdown-item" href="{{route('history.index', ['tournament' => $tournament->id, 'round' => $round->id])}}">Ronde: {{$round->name}}</a>
                                @endforeach
                            </div>
                        </div>
                    </h3>

                    <div class="card-columns mt-5">
                        @foreach($usedTables as $usedTable)
                            <div class="card">
                                <div class="card-header"><h5
                                        class="text-center card-title">{{$usedTable->name}}</h5>
                                </div>
                                <div class="card-body">
                                    <ul class="list-group list-group-flush">
                                        @foreach($users as $user)
                                            @if($user->pivot->table_id === $usedTable->id)
                                                <li style="{{Auth::user()->id === $user->id ? "background-color: #ededed" : ""}}"
                                                    class="list-group-item">{{$user->name}}<span
                                                        class="float-right">{{$user->scores()->where('round_id', $selectedRound->id)->first()->score}}</span>
                                                </li>
                                            @endif
                                        @endforeach
                                    </ul>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            @else
                <div class="col-md-8">
                    <div class="card mt-5">
                        <div class="card-header text-center text-danger">Ronde niet gevonden</div>
                        <div class="card-body">Deze ronde is nog niet gemaakt</div>
                    </div>
                </div>
            @endif
        </div>
    </div>
@endsection

resources/views/tableOverview.blade.php
@extends('layouts.app')

@section('content')

    <link href="{{ asset('css/tableOverview.css') }}" rel="stylesheet">

    <button class="btn btn-xs btn-outline-primary" id="back-to-search" title="Go to the search bar">Back to search</button>

    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="md-form mb-3 mt-0 text-center">
                    <form class="search-form" id="search-names">
                        <input ata-provide="typeahead" class="form-control typeahead border-primary"  id="search-box" type="text" placeholder="Firstname lastname" aria-label="Search" name="search">
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            @if($tables && $users != "[]")
                @foreach($tables as $table)
                    <div class="col-md-4 col-xs-12 table-mapping mb-4">
                        <div class="card">
                            <div class="card-header text-center">
                                {{ $table->table_id }}
                            </div>
                            <div class="card-body">
                                <div class="list-group-flush">
                                    @foreach($users as $user)
                                        @if($user->table_id == $table->table_id)
                                            <li class="list-group-item names" id="{{ $user->name }}">{{ $user->name }}</li>
                                        @endif
                                    @endforeach
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
            @else
                <div class="col-12 text-center">
                    <h2>Er zijn nog geen spelers toegevoegd aan de tafels voor de komende ronde.</h2>
                </div>
            @endif
        </div>
    </div>

@endsection

resources/views/timer.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/timer.css') }}" rel="stylesheet">
</head>
<body>
<div class="flex-center position-ref full-height">
    <div class="content">
        <div style="font-size: 20vw; font-size: 20vh" id="timer" class="title m-b-md" data-url="{{route('gettime',$tournament)}}">
            00:00:00
        </div>
    </div>
</div>
</body>
</html>