routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@show')->name('welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['role:speler']], function () {
        Route::prefix("tournament")->group(function () {
            Route::resource('signup', 'TournamentUserController');
    });
});
Route::get('tournament/employee/dashboard', function (){
    return redirect()->route('employee.dashboard',['tournament' => \App\Tournament::first()]);
});
Route::group(['prefix' => 'tournaments/{tournament}', 'middleware' => 'role:medewerker|admin'], function() {
    Route::get('/employee/dashboard', 'EmployeesController@index')->name('employee.dashboard');

    Route::get('rounds', 'RoundController@store')->name('round.store');
    Route::put('rounds/{round}', 'RoundController@update')->name('round.update');
    Route::get('rounds/{round}', 'RoundController@show')->name('round.show');
});

Route::group(['middleware' => ['role:admin']], function () {
    Route::resource('tournament', 'TournamentController')->only([
        'create', 'store'
    ]);

});

// Table overview
Route::get('{tournament}/overview', 'TableOverview@show')->name('show.tables');

Route::get('/{tournament}/overview/players', function ($tournament) {

    $latestRound = \App\Round::where('tournament_id', '=',  $tournament)->orderBy('name' ,'desc')->get('id')->first();

    $users = \App\UserRoundTable::join('tournament_user', 'user_round_table.user_id', '=', 'tournament_user.user_id')
        ->join('users', 'tournament_user.user_id', '=', 'users.id')
        ->select('users.name', 'user_round_table.table_id')
        ->where([['user_round_table.round_id', '=', $latestRound->id], ['tournament_user.tournament_id', '=', $tournament], ['tournament_user.status', '=', 1]])
        ->get();

    return $users;

});

//New Route naming.
Route::prefix("tournament/{tournament}")->group(function () {
    Route::prefix("round")->group(function () {
        Route::prefix("{round}")->group(function () {
            Route::resource("history", "UserRoundHistoryController");
        });
    });
});

Route::prefix("{tournament}")->group(function () {
    Route::get('/timer', 'TournamentController@timer')->name('timer');
    Route::get('/gettime', 'TournamentController@gettime')->name('gettime');
    Route::get('/stoptime', 'TournamentController@gettime')->name('stoptime');

    Route::group(['middleware' => ['role:speler']], function () {
        Route::get('/generalranking', 'GeneralRankingController@index')->name('generalranking');

    });
    Route::group(['middleware' => ['role:medewerker|admin']], function () {
        Route::resource('/scanner', 'QrScannerController');
        Route::prefix("employee")->group(function () {
            Route::resource("signups", "TournamentUserEmployeeController");
            Route::resource("score", "ScoreController")->only(['create', 'store']);
            Route::post("score/mail", "ScoreController@mail")->name('score.mail');


            //JS Fetch route
            Route::get('/{table}/round/players', function (\App\Tournament $tournament, \App\Table $table) {

                $table = $tournament->rounds()->orderByDesc("id")->first()->tables()->findOrFail($table->id);
                $users = $table->users(\App\Round::find($table->pivot["round_id"]))->get();

                return $users;

            })->name("round.players");
        });
    });
});
// Audio file path

Route::get('media/{filename}', function ($filename) {
    $path = storage_path('app/public/audio/' . $filename);

    if(!File::exists($path)) abort(404);

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});

app/Http/Controllers/EmployeesController.php
<?php

namespace App\Http\Controllers;

use App\Round;
use App\Tournament;
use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\Builder;

class EmployeesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Tournament $tournament)
    {
        $rounds = Round::all();

        // kan dit netter?
        $currentRoundHasEmptyScores = null;

        if($rounds->isNotEmpty()) {
            $currentRoundHasEmptyScores = $rounds->last()->emptyScores()->count() !== 0;
        }

        return view('employee.dashboard', [
            'rounds' => $rounds,
            'tournament' => $tournament,
            'currentRoundHasEmptyScores' => $currentRoundHasEmptyScores,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/employee/dashboard.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card mb-3">
                    <div class="card-header">
                        Eind resultaat mailen naar alle Admins
                    </div>

                    <div class="card-body">
                        <div class="col-12 text-center">
                            @if($errors->has('email_success'))
                                <h4 class="alert alert-success">{{$errors->first('email_success')}}</h4>
                            @endif
                        </div>
                        <form id="logout-form" action="{{ route('score.mail', $tournament->id) }}" method="POST">
                            @csrf
                            <button type="submit" class="btn btn-success">
                                Mailen
                            </button>
                        </form>

                    </div>
                </div>
                <div class="card mb-3">
                    <div class="card-header">
                        Nieuwe ronde aanmaken
                    </div>

                    <div class="card-body">
                        <a href="{{ route("round.store", $tournament->id) }}"
                           class="btn btn-success {{ $currentRoundHasEmptyScores ? 'disabled' : '' }}"
                        >
                            Genereren
                        </a>

                        @error('users')
                        <div class="alert alert-danger mt-3" role="alert">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                </div>
                @if(!$rounds->isEmpty())
                    <div class="card">
                        <div class="card-header">
                            Rondes
                        </div>
                        <div class="card-body">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">Aangemaakt op</th>
                                        <th scope="col">Ronde overzicht</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($rounds as $round)
                                        <tr class="round__edit" data-url="{{ route('round.update',  [
                                            'tournament' => $tournament->id,
                                            'round' => $round->id
                                        ]) }}">
                                            <th scope="row">{{ $round->id }}</th>
                                            <td>{{ $round->created_at }}</td>
                                            <td>
                                                @switch($round->status)
                                                    @case('inprogress')
                                                        @if($round->deadline === null)
                                                            <a href="{{ route('timer', $tournament) }}" class="btn btn-success js-start-timer">Timer Starten</a>
                                                        @else
                                                            <a href="{{ route('timer', $tournament) }}" class="btn btn-primary" >Timer bekijken</a>

                                                            <button class="btn btn-warning js-stop-timer" data-value="stopped">
                                                                Timer stoppen
                                                            </button>
                                                        @endif
                                                        @break
                                                    @case('stopped')
                                                        @if($rounds->last()->id === $round->id && $round->emptyScores()->count())
                                                            <a href="{{ route('score.create', $tournament->id) }}" class="btn btn-primary">Punten invullen</a>
                                                        @endif
                                                        <a href="{{ route('round.show', [
                                                            'tournament' => $tournament->id,
                                                            'round' => $round->id
                                                        ]) }}" class="btn btn-link">Ronde inzien</a>
                                                        @break
                                                    @default
                                                        <button class="btn btn-success js-start-round" data-value="inprogress">Ronde starten</button>
                                                @endswitch
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                @endif
            </div>
        </div>
    </div>
@endsection

resources/views/employee/score.blade.php
@extends("layouts.app")

@section("content")

@foreach($errors as $error)
    $error
    @endforeach
    <div class="container">
        <div class="row">
            <div class="col-6 offset-3">
                @if (session('message'))
                    <div class="alert alert-{{session('message')['type']}}">
                        {{ session('message')['content'] }}
                    </div>
                @endif
                {!! Form::open(['method'=>'post','route'=>['score.store',$tournament]]) !!}
                    <div class="form-group">
                        {!! Form::label('table','Tafel:') !!}
                        {!! Form::select('table',$tables,null,["placeholder"=>"Selecteer een tafel","class"=>"custom-select"]) !!}
                    </div>
                    <div class="player-scores">

                    </div>
                {!! Form::submit("Invullen",['class'=>'btn btn-primary']) !!}
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/employee/useroverview.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                @if($tournamentUsers->first() != null)
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Aangemelde spelers voor het toernooi:</h4>
                        </div>
                        <div class="card-body">
                            <div class="m-1">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th scope="col">Naam</th>
                                        <th scope="col">Datum aangemeld</th>
                                        <th scope="col">Afmelden</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($tournamentUsers as $tournamentUser)
                                        <tr>
                                            <td>{{ $tournamentUser->name }}</td>
                                            <td>{{ date_format(date_create($tournamentUser->pivot->created_at),"d-m-Y") }}</td>

                                            <td>{!! Form::open(['method' => 'DELETE', 'route' => ['signups.destroy',$tournament, 1,$tournamentUser->pivot->id]]) !!}
                                                {!! Form::submit('Speler Afmelden', ['class'=>'btn btn-danger','onclick' => 'return confirm("Weet je zeker dat je deze gebruiker wilt uitschrijven?");']) !!}
                                                {!! Form::close() !!}</td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                                <div>{{ $tournamentUsers->links() }}</div>
                            </div>
                        </div>
                    </div>
                @else
                <div class="card">
                    <div class="card-header text-center">Geen aanmeldingen voor dit toernooi</div>
                </div>

                @endif
            </div>
        </div>
    </div>
@endsection